services:
  web-app:
    image: nginx:alpine
    container_name: devops-app
    restart: always
    volumes:
      - ./index.html:/usr/share/nginx/html
    networks:
      - web_network

networks:
  web_network:
    external: true
